#!/bin/bash

set -euo pipefail
trap 'rc=$?;set +ex;if [[ $rc -ne 0 ]];then trap - ERR EXIT;echo 1>&2;echo "*** fail *** : code $rc : $DIR/$SCRIPT $ARGS" 1>&2;echo 1>&2;exit $rc;fi' ERR EXIT
ARGS="$*"
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SCRIPT="$(basename "${BASH_SOURCE[0]}")"

name=tinybook2

cd ${DIR}/src/app

set -x

pwd

docker run -it --rm --mount type=bind,src=$(pwd),dst=/app -p 8000:8000 --name $name docker.io/hughsw/$name "$@"

#docker run -it --rm -p 8000:8000 --name $name docker.io/hughsw/$name "$@"
